# This workflow will install Python dependencies, and build the app
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Ubuntu dependencies
      run: >
        sudo apt-get update -q && sudo apt-get install
        --no-install-recommends -y xvfb python3-dev python3-gi
        python3-gi-cairo gir1.2-gtk-3.0 libgirepository1.0-dev libcairo2-dev
        intltool
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade keyrings.alt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build wheel and Install
      run: |
        pip install .
    - name: Build source distribution
      run: |
        python setup.py sdist
    - name: Verify internationalization
      run: |
          python setup.py build_i18n
    - name: Verify icons packaging
      run: |
          python setup.py build_icons
