# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Ubuntu dependencies
      run: |
        sudo apt-get -y install python3-distutils-extra python3-gi python3-gi-cairo gobject-introspection gir1.2-gtk-3.0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 nose
        pip install --upgrade keyrings.alt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with nose
      run: |
        nosetests gourmet/tests/test_*
